expert: compute-serverless
sources:
  - url: https://cloud.google.com/run/docs/overview/what-is-cloud-run
    pillar: operational-excellence
  - url: https://cloud.google.com/run/docs/about-instance-autoscaling
    pillar: performance-efficiency
  - url: https://cloud.google.com/functions/docs/concepts/overview
    pillar: operational-excellence
  - url: https://cloud.google.com/functions/docs/concepts/execution-environment
    pillar: reliability
  - url: https://cloud.google.com/appengine/docs/an-overview-of-app-engine
    pillar: operational-excellence
  - url: https://cloud.google.com/workflows/docs/overview
    pillar: reliability
  - url: https://cloud.google.com/run/docs/securing/service-identity
    pillar: security-compliance
  - url: https://cloud.google.com/run/docs/configuring/min-instances
    pillar: performance-efficiency
  - url: https://cloud.google.com/run/docs/jobs/create-execute
    pillar: operational-excellence
